// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessGame.Models
{
    public partial class CartProduct
    {
        public int Id { get; set; }
        public int? IdCart { get; set; }
        public int? IdProduct { get; set; }
        public int? Quantity { get; set; }

        public virtual Carts IdCartNavigation { get; set; }
        public virtual Products IdProductNavigation { get; set; }
    }
}