// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessGame.Models
{
    public partial class Carts
    {
        public Carts()
        {
            CartProduct = new HashSet<CartProduct>();
        }

        public int Id { get; set; }
        public int? IdUser { get; set; }

        public virtual Users IdUserNavigation { get; set; }
        public virtual ICollection<CartProduct> CartProduct { get; set; }
    }
}