// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessGame.Models
{
    public partial class Products
    {
        public Products()
        {
            CartProduct = new HashSet<CartProduct>();
            Shops = new HashSet<Shops>();
        }

        public int Id { get; set; }
        public string Nome { get; set; }
        public decimal? Prezzo { get; set; }
        public int? Quantita { get; set; }

        public virtual ICollection<CartProduct> CartProduct { get; set; }
        public virtual ICollection<Shops> Shops { get; set; }
    }
}