// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessGame.Models
{
    public partial class Shops
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public int? IdProduct { get; set; }

        public virtual Products IdProductNavigation { get; set; }
    }
}