// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessGame.Models
{
    public partial class Users
    {
        public Users()
        {
            Carts = new HashSet<Carts>();
        }

        public int Id { get; set; }
        public string Nome { get; set; }

        public virtual ICollection<Carts> Carts { get; set; }
    }
}